import type { Database } from '../../src/types/database.ts'

type Enums = Database['public']['Enums']

export type SeedJob = {
  /** Stable key so re-running the seed updates the same rows. */
  key: string
  company: string
  title: string
  location: string
  remote?: boolean
  pay: [number, number]
  period?: Enums['pay_period']
  level: Enums['experience_level']
  type?: Enums['employment_type']
  skills: string[]
  daysAgo: number
  status?: Enums['job_status']
  summary: string
  duties: string[]
}

export const JOBS: SeedJob[] = [
  // Lumen AI (the demo recruiter's company)
  {
    key: 'lumen-frontend',
    company: 'lumen-ai',
    title: 'Frontend Engineer',
    location: 'San Francisco, CA',
    remote: true,
    pay: [150_000, 185_000],
    level: 'mid',
    skills: ['React', 'TypeScript', 'GraphQL', 'Tailwind CSS'],
    daysAgo: 3,
    summary: 'Own the analyst workspace, the canvas where our customers and our models collaborate.',
    duties: [
      'Build fast, keyboard-first interfaces for dense financial data',
      'Design streaming UI patterns for model output',
      'Partner with design to evolve our component system',
    ],
  },
  {
    key: 'lumen-senior-frontend',
    company: 'lumen-ai',
    title: 'Senior Frontend Engineer',
    location: 'Remote (US)',
    remote: true,
    pay: [180_000, 220_000],
    level: 'senior',
    skills: ['React', 'TypeScript', 'Performance', 'Design Systems'],
    daysAgo: 6,
    summary: 'Set the technical direction for our web app as we scale from hundreds to thousands of seats.',
    duties: [
      'Lead architecture for our React application',
      'Mentor engineers and raise the bar on quality',
      'Drive performance work on large, virtualized tables',
    ],
  },
  {
    key: 'lumen-ml-engineer',
    company: 'lumen-ai',
    title: 'Machine Learning Engineer, Retrieval',
    location: 'San Francisco, CA',
    pay: [200_000, 260_000],
    level: 'senior',
    skills: ['Python', 'PyTorch', 'Search', 'LLMs'],
    daysAgo: 10,
    summary: 'Make our models find the right number in a 300-page 10-K every time.',
    duties: [
      'Build retrieval and ranking pipelines over financial documents',
      'Design evals that reflect real analyst workflows',
      'Ship improvements from notebook to production',
    ],
  },
  {
    key: 'lumen-product-designer',
    company: 'lumen-ai',
    title: 'Product Designer',
    location: 'San Francisco, CA',
    pay: [160_000, 195_000],
    level: 'mid',
    skills: ['Figma', 'Prototyping', 'Design Systems'],
    daysAgo: 1,
    status: 'draft',
    summary: 'Design how analysts and AI work together on the same page.',
    duties: [
      'Own end-to-end design for core workflows',
      'Prototype interactions for AI-generated content',
      'Run research sessions with analysts',
    ],
  },
  {
    key: 'lumen-intern',
    company: 'lumen-ai',
    title: 'Software Engineering Intern',
    location: 'San Francisco, CA',
    pay: [55, 60],
    period: 'hour',
    level: 'intern',
    type: 'internship',
    skills: ['TypeScript', 'Python', 'React'],
    daysAgo: 40,
    status: 'closed',
    summary: 'Spend the summer shipping real features with a mentor by your side.',
    duties: [
      'Ship a meaningful project end to end',
      'Pair with engineers across the stack',
      'Present your work to the whole company',
    ],
  },

  // Parcel
  {
    key: 'parcel-product-engineer',
    company: 'parcel',
    title: 'Product Engineer, Growth',
    location: 'San Francisco, CA',
    pay: [160_000, 195_000],
    level: 'mid',
    skills: ['React', 'TypeScript', 'Node.js', 'Postgres'],
    daysAgo: 2,
    summary: 'Turn first-time API users into lifelong customers.',
    duties: [
      'Build onboarding and self-serve billing flows',
      'Run experiments and read the data yourself',
      'Work across our Next.js dashboard and Node services',
    ],
  },
  {
    key: 'parcel-backend',
    company: 'parcel',
    title: 'Backend Engineer, Carrier Integrations',
    location: 'Remote (US)',
    remote: true,
    pay: [155_000, 190_000],
    level: 'mid',
    skills: ['Go', 'Postgres', 'Distributed Systems'],
    daysAgo: 8,
    summary: 'Connect Parcel to every carrier on earth, reliably.',
    duties: [
      'Build and maintain carrier integrations in Go',
      'Design for idempotency and failure at scale',
      'Improve observability across our pipeline',
    ],
  },
  {
    key: 'parcel-staff',
    company: 'parcel',
    title: 'Staff Engineer, Platform',
    location: 'San Francisco, CA',
    pay: [230_000, 280_000],
    level: 'lead',
    skills: ['Go', 'Kubernetes', 'AWS', 'Distributed Systems'],
    daysAgo: 15,
    summary: 'Shape the platform that moves millions of packages a day.',
    duties: [
      'Set multi-year technical strategy for platform',
      'Lead cross-team reliability initiatives',
      'Mentor senior engineers',
    ],
  },
  {
    key: 'parcel-support',
    company: 'parcel',
    title: 'Technical Support Engineer',
    location: 'Chicago, IL',
    pay: [85_000, 105_000],
    level: 'entry',
    skills: ['APIs', 'SQL', 'Customer Support'],
    daysAgo: 5,
    summary: 'Be the engineer our customers trust when packages go sideways.',
    duties: [
      'Debug integration issues with customers',
      'Write internal tools and runbooks',
      'Feed insights back to product',
    ],
  },
  {
    key: 'parcel-data-analyst',
    company: 'parcel',
    title: 'Data Analyst',
    location: 'San Francisco, CA',
    pay: [110_000, 135_000],
    level: 'entry',
    skills: ['SQL', 'Python', 'dbt', 'Looker'],
    daysAgo: 12,
    summary: 'Help every team at Parcel make decisions with data.',
    duties: [
      'Own dashboards for revenue and shipping volume',
      'Model data in dbt',
      'Partner with ops on carrier performance analysis',
    ],
  },

  // Fernhill Health
  {
    key: 'fernhill-fullstack',
    company: 'fernhill-health',
    title: 'Full-Stack Engineer',
    location: 'New York, NY',
    pay: [150_000, 185_000],
    level: 'mid',
    skills: ['React', 'TypeScript', 'Ruby on Rails', 'Postgres'],
    daysAgo: 4,
    summary: 'Build the tools our clinicians use to care for thousands of patients a day.',
    duties: [
      'Ship features across our Rails API and React apps',
      'Work closely with clinicians on workflow design',
      'Uphold HIPAA-grade security practices',
    ],
  },
  {
    key: 'fernhill-ios',
    company: 'fernhill-health',
    title: 'Senior iOS Engineer',
    location: 'New York, NY',
    remote: true,
    pay: [175_000, 215_000],
    level: 'senior',
    skills: ['Swift', 'SwiftUI', 'iOS'],
    daysAgo: 9,
    summary: "Own the app that's the front door to Fernhill for our patients.",
    duties: [
      'Lead development of our SwiftUI app',
      'Build video visit and messaging experiences',
      'Champion accessibility',
    ],
  },
  {
    key: 'fernhill-designer',
    company: 'fernhill-health',
    title: 'Senior Product Designer',
    location: 'New York, NY',
    pay: [165_000, 200_000],
    level: 'senior',
    skills: ['Figma', 'User Research', 'Design Systems'],
    daysAgo: 14,
    summary: 'Make healthcare feel human, one flow at a time.',
    duties: [
      'Lead design for the patient app',
      'Run research with patients and clinicians',
      'Evolve our design system',
    ],
  },
  {
    key: 'fernhill-coordinator',
    company: 'fernhill-health',
    title: 'Care Operations Associate',
    location: 'New York, NY',
    pay: [28, 34],
    period: 'hour',
    level: 'entry',
    type: 'part_time',
    skills: ['Operations', 'Customer Support'],
    daysAgo: 6,
    summary: 'Keep our care teams and patients moving smoothly.',
    duties: [
      'Coordinate scheduling and follow-ups',
      'Resolve patient questions quickly and kindly',
      'Improve operational playbooks',
    ],
  },
  {
    key: 'fernhill-data-engineer',
    company: 'fernhill-health',
    title: 'Data Engineer',
    location: 'Remote (US)',
    remote: true,
    pay: [150_000, 180_000],
    level: 'mid',
    skills: ['Python', 'SQL', 'dbt', 'Airflow'],
    daysAgo: 20,
    summary: 'Build the data platform behind better patient outcomes.',
    duties: [
      'Own pipelines from EHR and claims sources',
      'Model clinical data for analytics',
      'Ensure data quality and privacy',
    ],
  },

  // Quarry
  {
    key: 'quarry-founding-frontend',
    company: 'quarry',
    title: 'Founding Frontend Engineer',
    location: 'Remote (Global)',
    remote: true,
    pay: [160_000, 200_000],
    level: 'senior',
    skills: ['React', 'TypeScript', 'Data Visualization'],
    daysAgo: 2,
    summary: 'Be the first frontend hire and define how data engineers see their pipelines.',
    duties: [
      'Build our lineage graph and run explorer',
      'Set up frontend foundations from scratch',
      'Talk to users every week',
    ],
  },
  {
    key: 'quarry-rust',
    company: 'quarry',
    title: 'Systems Engineer (Rust)',
    location: 'Remote (Global)',
    remote: true,
    pay: [170_000, 210_000],
    level: 'senior',
    skills: ['Rust', 'Distributed Systems', 'SQL'],
    daysAgo: 11,
    summary: 'Build the execution engine at the heart of Quarry.',
    duties: [
      'Design a fast, correct pipeline executor in Rust',
      'Optimize query planning and scheduling',
      'Write the kind of code other engineers learn from',
    ],
  },
  {
    key: 'quarry-devrel',
    company: 'quarry',
    title: 'Developer Advocate',
    location: 'Remote (US)',
    remote: true,
    pay: [130_000, 160_000],
    level: 'mid',
    skills: ['Python', 'SQL', 'Technical Writing'],
    daysAgo: 7,
    summary: 'Teach the data world how to ship pipelines with confidence.',
    duties: [
      'Write tutorials, docs and example projects',
      'Speak at meetups and conferences',
      'Bring community feedback to the roadmap',
    ],
  },
  {
    key: 'quarry-contract-docs',
    company: 'quarry',
    title: 'Technical Writer (Contract)',
    location: 'Remote (Global)',
    remote: true,
    pay: [70, 90],
    period: 'hour',
    level: 'mid',
    type: 'contract',
    skills: ['Technical Writing', 'SQL', 'Python'],
    daysAgo: 18,
    summary: 'Help us rebuild our documentation from the ground up.',
    duties: [
      'Restructure our docs information architecture',
      'Write guides for core workflows',
      'Set up a docs style guide',
    ],
  },
  {
    key: 'quarry-intern',
    company: 'quarry',
    title: 'Engineering Intern',
    location: 'Remote (US)',
    remote: true,
    pay: [45, 50],
    period: 'hour',
    level: 'intern',
    type: 'internship',
    skills: ['Python', 'SQL', 'TypeScript'],
    daysAgo: 4,
    summary: 'Ship real features to real users, fully remote.',
    duties: [
      'Own a project from spec to launch',
      'Pair with our founding team',
      'Learn how a dev tools startup is built',
    ],
  },

  // Tandem
  {
    key: 'tandem-web',
    company: 'tandem',
    title: 'Software Engineer, Web',
    location: 'New York, NY',
    pay: [140_000, 170_000],
    level: 'mid',
    skills: ['React', 'TypeScript', 'Node.js'],
    daysAgo: 5,
    summary: 'Build the web experience couples use to plan their financial life together.',
    duties: [
      'Ship features across onboarding, goals and budgeting',
      'Build secure, accessible money flows',
      'Collaborate closely with mobile and design',
    ],
  },
  {
    key: 'tandem-mobile',
    company: 'tandem',
    title: 'Mobile Engineer (React Native)',
    location: 'New York, NY',
    remote: true,
    pay: [145_000, 175_000],
    level: 'mid',
    skills: ['React Native', 'TypeScript', 'iOS', 'Android'],
    daysAgo: 13,
    summary: 'Own the app at the center of Tandem.',
    duties: [
      'Build delightful, fast mobile experiences',
      'Own release quality and app performance',
      'Shape our shared component library',
    ],
  },
  {
    key: 'tandem-risk',
    company: 'tandem',
    title: 'Risk Analyst',
    location: 'New York, NY',
    pay: [95_000, 120_000],
    level: 'entry',
    skills: ['SQL', 'Python', 'Fraud'],
    daysAgo: 9,
    summary: 'Keep Tandem members safe from fraud without getting in their way.',
    duties: [
      'Monitor and investigate suspicious activity',
      'Build rules and dashboards',
      'Work with engineering on risk tooling',
    ],
  },
  {
    key: 'tandem-em',
    company: 'tandem',
    title: 'Engineering Manager, Core Banking',
    location: 'New York, NY',
    pay: [210_000, 250_000],
    level: 'lead',
    skills: ['Leadership', 'Fintech', 'Distributed Systems'],
    daysAgo: 22,
    summary: 'Lead the team that moves every dollar at Tandem.',
    duties: [
      'Manage and grow a team of six engineers',
      'Partner with compliance and our bank partners',
      'Own reliability for money movement',
    ],
  },
  {
    key: 'tandem-designer',
    company: 'tandem',
    title: 'Brand Designer',
    location: 'New York, NY',
    pay: [120_000, 145_000],
    level: 'mid',
    skills: ['Brand', 'Illustration', 'Figma'],
    daysAgo: 16,
    summary: 'Make money feel warm, fun and a little bit romantic.',
    duties: [
      'Own brand across product, marketing and social',
      'Create illustration and motion systems',
      'Ship campaigns end to end',
    ],
  },

  // Orbital
  {
    key: 'orbital-fullstack',
    company: 'orbital',
    title: 'Full-Stack Engineer',
    location: 'Austin, TX',
    pay: [135_000, 165_000],
    level: 'mid',
    skills: ['React', 'TypeScript', 'Python', 'Postgres'],
    daysAgo: 3,
    summary: 'Build the map logistics teams stare at all day.',
    duties: [
      'Build real-time tracking views with mapping libraries',
      'Own APIs in Python and Postgres',
      'Work directly with customers',
    ],
  },
  {
    key: 'orbital-geo',
    company: 'orbital',
    title: 'Geospatial Data Scientist',
    location: 'Austin, TX',
    remote: true,
    pay: [150_000, 185_000],
    level: 'senior',
    skills: ['Python', 'Geospatial', 'Machine Learning'],
    daysAgo: 10,
    summary: 'Predict delays before they happen using satellite and IoT data.',
    duties: [
      'Build ETA and anomaly models',
      'Fuse noisy data sources into ground truth',
      'Ship models to production with engineering',
    ],
  },
  {
    key: 'orbital-sre',
    company: 'orbital',
    title: 'Site Reliability Engineer',
    location: 'Seattle, WA',
    pay: [160_000, 195_000],
    level: 'senior',
    skills: ['Kubernetes', 'AWS', 'Terraform', 'Observability'],
    daysAgo: 17,
    summary: 'Keep real-time tracking real-time.',
    duties: [
      'Own uptime and on-call health',
      'Automate infrastructure with Terraform',
      'Lead incident response and postmortems',
    ],
  },
  {
    key: 'orbital-sales-eng',
    company: 'orbital',
    title: 'Solutions Engineer',
    location: 'Chicago, IL',
    pay: [120_000, 150_000],
    level: 'mid',
    skills: ['APIs', 'SQL', 'Customer Success'],
    daysAgo: 6,
    summary: 'Be the technical partner for our largest logistics customers.',
    duties: [
      'Lead technical discovery and demos',
      'Scope and support integrations',
      'Turn customer needs into product feedback',
    ],
  },
  {
    key: 'orbital-junior',
    company: 'orbital',
    title: 'Junior Software Engineer',
    location: 'Austin, TX',
    pay: [100_000, 120_000],
    level: 'entry',
    skills: ['Python', 'JavaScript', 'SQL'],
    daysAgo: 1,
    summary: 'Start your career on a team that ships every day.',
    duties: [
      'Ship features with support from a mentor',
      'Learn our stack from frontend to data',
      'Participate in code review and on-call (shadowing)',
    ],
  },

  // Basalt Security
  {
    key: 'basalt-security-engineer',
    company: 'basalt-security',
    title: 'Security Engineer',
    location: 'Boston, MA',
    pay: [165_000, 200_000],
    level: 'senior',
    skills: ['Cloud Security', 'AWS', 'Go'],
    daysAgo: 4,
    summary: 'Find attack paths before attackers do.',
    duties: [
      'Research cloud attack techniques',
      'Turn research into detection logic',
      'Advise customers on remediation',
    ],
  },
  {
    key: 'basalt-frontend',
    company: 'basalt-security',
    title: 'Frontend Engineer, Graph UI',
    location: 'Boston, MA',
    remote: true,
    pay: [145_000, 175_000],
    level: 'mid',
    skills: ['React', 'TypeScript', 'D3', 'WebGL'],
    daysAgo: 12,
    summary: 'Visualize cloud infrastructures with millions of nodes.',
    duties: [
      'Build our interactive attack-path graph',
      'Push the limits of browser rendering performance',
      'Collaborate with security researchers',
    ],
  },
  {
    key: 'basalt-backend',
    company: 'basalt-security',
    title: 'Backend Engineer',
    location: 'Boston, MA',
    pay: [150_000, 180_000],
    level: 'mid',
    skills: ['Go', 'Postgres', 'Graph Databases'],
    daysAgo: 19,
    summary: 'Build the graph engine that powers Basalt.',
    duties: [
      'Ingest and model cloud configuration at scale',
      'Optimize graph queries',
      'Own services end to end',
    ],
  },
  {
    key: 'basalt-pm',
    company: 'basalt-security',
    title: 'Product Manager',
    location: 'Boston, MA',
    pay: [160_000, 190_000],
    level: 'senior',
    skills: ['Product Management', 'Security', 'B2B SaaS'],
    daysAgo: 8,
    summary: 'Decide what security teams should fix first, and why.',
    duties: [
      'Own the prioritization and remediation roadmap',
      'Talk to CISOs and security engineers weekly',
      'Write crisp specs and measure outcomes',
    ],
  },
  {
    key: 'basalt-intern',
    company: 'basalt-security',
    title: 'Security Research Intern',
    location: 'Boston, MA',
    pay: [40, 48],
    period: 'hour',
    level: 'intern',
    type: 'internship',
    skills: ['Python', 'Cloud Security', 'Linux'],
    daysAgo: 25,
    summary: 'Spend a summer hunting real cloud misconfigurations.',
    duties: [
      'Research a novel cloud attack technique',
      'Build detection prototypes',
      'Publish findings on our blog',
    ],
  },

  // Kite & Co
  {
    key: 'kite-design-engineer',
    company: 'kite-and-co',
    title: 'Design Engineer',
    location: 'Los Angeles, CA',
    remote: true,
    pay: [140_000, 175_000],
    level: 'mid',
    skills: ['React', 'TypeScript', 'CSS', 'Figma'],
    daysAgo: 2,
    summary: 'Live where design and code meet, and make both better.',
    duties: [
      'Build our token pipeline and component generators',
      'Prototype interactions in code',
      'Obsess over details',
    ],
  },
  {
    key: 'kite-plugin',
    company: 'kite-and-co',
    title: 'Figma Plugin Engineer (Contract)',
    location: 'Remote (US)',
    remote: true,
    pay: [85, 110],
    period: 'hour',
    level: 'senior',
    type: 'contract',
    skills: ['TypeScript', 'Figma', 'React'],
    daysAgo: 9,
    summary: 'Build the Figma plugin that kicks off every Kite project.',
    duties: [
      'Architect and ship our Figma plugin',
      'Sync design tokens with our API',
      'Document the plugin for customers',
    ],
  },
  {
    key: 'kite-designer',
    company: 'kite-and-co',
    title: 'Product Designer',
    location: 'Los Angeles, CA',
    pay: [125_000, 155_000],
    level: 'mid',
    skills: ['Figma', 'Design Systems', 'Prototyping'],
    daysAgo: 5,
    summary: 'Design the tool that designers use to design.',
    duties: [
      'Own flows across our web app and plugin',
      'Ship polished, opinionated UI',
      'Work directly with founders',
    ],
  },
  {
    key: 'kite-community',
    company: 'kite-and-co',
    title: 'Community Lead (Part-time)',
    location: 'Los Angeles, CA',
    remote: true,
    pay: [35, 45],
    period: 'hour',
    level: 'entry',
    type: 'part_time',
    skills: ['Community', 'Content', 'Design'],
    daysAgo: 21,
    summary: 'Grow a community of design-systems nerds.',
    duties: [
      'Run our Discord and monthly events',
      'Highlight community work',
      'Bring feedback to the product team',
    ],
  },
  {
    key: 'kite-founding-backend',
    company: 'kite-and-co',
    title: 'Founding Backend Engineer',
    location: 'Los Angeles, CA',
    pay: [165_000, 200_000],
    level: 'senior',
    skills: ['Node.js', 'TypeScript', 'Postgres', 'AWS'],
    daysAgo: 7,
    summary: 'Build the API behind every generated design system.',
    duties: [
      'Design our core APIs and data model',
      'Own infrastructure and deploys',
      'Hire the next engineers with us',
    ],
  },
]

export function describeJob(job: SeedJob, companyName: string): string {
  return [
    job.summary,
    '',
    "What you'll do",
    ...job.duties.map((d) => `• ${d}`),
    '',
    "What we're looking for",
    `• Experience with ${job.skills.slice(0, -1).join(', ')}${job.skills.length > 1 ? ' and ' : ''}${job.skills.at(-1)}`,
    '• Clear written communication and a bias toward shipping',
    '• Curiosity about our customers and the problems they face',
    '',
    `Why ${companyName}`,
    '• Competitive salary and meaningful equity',
    '• Comprehensive health, dental and vision coverage',
    '• Flexible time off and a yearly learning budget',
  ].join('\n')
}
